;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	   ______      __
;;	  / ____/___  / /___  __________
;;	 / /   / __ \/ / __ \/ ___/ ___/
;;	/ /___/ /_/ / / /_/ / /  (__  )
;;	\____/\____/_/\____/_/  /____/
;;
;;   Colores activos — Tema s4vitar (default)
;;   Este archivo es actualizado por launch_theme.sh
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]
bg        = #CC0a0a0a
fg        = #FFFFFF
ac        = #FEC006
dim       = #806000

trans     = #00000000
white     = #FFFFFF
black     = #000000

;; Usados en módulos
red       = #e53935
gray      = #4a4a4a
orange    = #F16E44
cyan      = #00acc1
blue-gray = #546e7a
